spring:
  jpa:
    #콘솔에 SQL 출력
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    # 테이블 생성 후 data.sql 실행
    defer-datasource-initialization: true

  # h2 DB 접속정보
  datasource:
    url: jdbc:h2:mem:testdb

  # h2 DB툴을 브라우저에서 사용가능
  h2:
    console:
      enable: true

jwt:
  issuer: ironmask431@gmail.com
  secretKey: study-springboot

